### ISSUE TITLE
iOS CPP 编译出错

### ISSUE THREAD

**Issue by wanghuan1115** [sdkbox/sdkbox-facebook-sample-v2#4]
### facebook-v2 版本: 1.5.0.2

2.x 无法使用cocos命令行编译，使用xcode编译时出错

错误信息:

~~~
/Users/qeeplay/Documents/chukong_test/sdkbox-facebook-sample-v2/projects/FacebookSample/Classes/HelloWorldScene.h:20:17: Allocating an object of abstract class type 'HelloWorld'
~~~

**Comment by yinjimmy** [comment]
fixed with commit https://github.com/sdkbox/sdkbox-facebook-sample-v2/commit/ed35d237328f7b9708415c3b1b5b2469835eb331
